/**
 * Central declarative dataset for default event classification.
 *
 * This file contains only maintained knowledge about common digital services.
 * It intentionally contains NO classification logic; matching is implemented
 * in DefaultClassificationRules.ts.
 *
 * Dimension values must match the names stored in classification_dimensions.
 * If a dimension name does not exist at runtime, the classifier resolves it to
 * null rather than inventing an invalid ID.
 *
 * Context is never assigned automatically. All entries leave contextId as null.
 */

export interface DefaultClassificationEntry {
  id: string;
  /** Human-readable name used in explainability, e.g. "Default: Netflix". */
  name: string;
  /** Canonical application names. Matching is normalized for case/aliases. */
  apps?: string[];
  /** Canonical domains. Matching normalizes www, case, and subdomains. */
  domains?: string[];
  /** Target area dimension name (must exist in classification_dimensions). */
  area: string;
  /** Target intent dimension name (must exist in classification_dimensions). */
  intent: string;
  /** Target quality dimension name (must exist in classification_dimensions). */
  quality: string;
  /** High = auto-classify on app or domain. Medium = exact app/domain only. Low = never auto-classify. */
  confidence: 'high' | 'medium' | 'low';
  /** Organizing category for maintenance; not exposed to users. */
  category:
    | 'development'
    | 'learning'
    | 'communication'
    | 'entertainment'
    | 'social'
    | 'shopping'
    | 'productivity'
    | 'ai'
    | 'news'
    | 'gaming'
    | 'other';
  /** Optional tie-break priority. Higher numbers win. */
  priority?: number;
  /** Maintenance notes explaining non-obvious choices. */
  notes?: string;
}

// NOTE: Search engines (google.com, bing.com, duckduckgo.com) are intentionally
// excluded because search intent cannot be reliably inferred from the domain.

export const DEFAULT_CLASSIFICATION_DATA: DefaultClassificationEntry[] = [
  // ── Development / Engineering ─────────────────────────────────────────────
  {
    id: 'vscode',
    name: 'Visual Studio Code',
    apps: ['Visual Studio Code'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },
  {
    id: 'visual_studio',
    name: 'Visual Studio',
    apps: ['Visual Studio'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },
  {
    id: 'github',
    name: 'GitHub',
    domains: ['github.com'],
    apps: ['GitHub Desktop'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    domains: ['gitlab.com'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    domains: ['bitbucket.org'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },
  {
    id: 'docker_desktop',
    name: 'Docker Desktop',
    apps: ['Docker Desktop'],
    domains: ['docker.com'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },
  {
    id: 'postman',
    name: 'Postman',
    apps: ['Postman'],
    domains: ['postman.com'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },
  {
    id: 'insomnia',
    name: 'Insomnia',
    apps: ['Insomnia'],
    domains: ['insomnia.rest'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },
  {
    id: 'figma',
    name: 'Figma',
    apps: ['Figma'],
    domains: ['figma.com'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },
  {
    id: 'stack_overflow',
    name: 'Stack Overflow',
    domains: ['stackoverflow.com'],
    area: 'Work',
    intent: 'Research',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },
  {
    id: 'npm',
    name: 'npm',
    domains: ['npmjs.com'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },
  {
    id: 'pypi',
    name: 'PyPI',
    domains: ['pypi.org'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'development',
  },

  // ── Learning / Education ──────────────────────────────────────────────────
  // NOTE: The database does not currently have a "Learning" area, so these
  // map to "Work" as the most reasonable existing alternative. They can be
  // re-mapped automatically if a Learning area is added later.
  {
    id: 'udemy',
    name: 'Udemy',
    domains: ['udemy.com'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'coursera',
    name: 'Coursera',
    domains: ['coursera.org'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'edx',
    name: 'edX',
    domains: ['edx.org'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'skillshare',
    name: 'Skillshare',
    domains: ['skillshare.com'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'khan_academy',
    name: 'Khan Academy',
    domains: ['khanacademy.org'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'freecodecamp',
    name: 'freeCodeCamp',
    domains: ['freecodecamp.org'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'codecademy',
    name: 'Codecademy',
    domains: ['codecademy.com'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'leetcode',
    name: 'LeetCode',
    domains: ['leetcode.com'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'geeksforgeeks',
    name: 'GeeksforGeeks',
    domains: ['geeksforgeeks.org'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'mdn',
    name: 'MDN Web Docs',
    domains: ['developer.mozilla.org'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'react_docs',
    name: 'React Documentation',
    domains: ['react.dev'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'nextjs_docs',
    name: 'Next.js Documentation',
    domains: ['nextjs.org'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'nodejs_docs',
    name: 'Node.js Documentation',
    domains: ['nodejs.org'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'npm_docs',
    name: 'npm Documentation',
    domains: ['docs.npmjs.com'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'microsoft_learn',
    name: 'Microsoft Learn',
    domains: ['learn.microsoft.com'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'github_docs',
    name: 'GitHub Docs',
    domains: ['docs.github.com'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'w3schools',
    name: 'W3Schools',
    domains: ['w3schools.com'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },
  {
    id: 'python_docs',
    name: 'Python Documentation',
    domains: ['docs.python.org'],
    area: 'Work',
    intent: 'Learn',
    quality: 'Focused',
    confidence: 'high',
    category: 'learning',
  },

  // ── Entertainment / Streaming ─────────────────────────────────────────────
  {
    id: 'netflix',
    name: 'Netflix',
    domains: ['netflix.com'],
    apps: ['Netflix'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'entertainment',
  },
  {
    id: 'prime_video',
    name: 'Prime Video',
    domains: ['primevideo.com'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'entertainment',
  },
  {
    id: 'disney_plus',
    name: 'Disney+',
    domains: ['disneyplus.com'],
    apps: ['Disney+'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'entertainment',
  },
  {
    id: 'hulu',
    name: 'Hulu',
    domains: ['hulu.com'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'entertainment',
  },
  {
    id: 'max',
    name: 'Max',
    domains: ['max.com'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'entertainment',
  },
  {
    id: 'apple_tv',
    name: 'Apple TV+',
    domains: ['tv.apple.com'],
    apps: ['TV'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'entertainment',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    domains: ['spotify.com', 'open.spotify.com'],
    apps: ['Spotify'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'entertainment',
  },
  {
    id: 'youtube_music',
    name: 'YouTube Music',
    domains: ['music.youtube.com'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'entertainment',
  },
  {
    id: 'twitch',
    name: 'Twitch',
    domains: ['twitch.tv'],
    apps: ['Twitch'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'entertainment',
  },
  {
    id: 'crunchyroll',
    name: 'Crunchyroll',
    domains: ['crunchyroll.com'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'entertainment',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    domains: ['youtube.com'],
    apps: ['YouTube'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'entertainment',
  },

  // ── Gaming ────────────────────────────────────────────────────────────────
  {
    id: 'steam',
    name: 'Steam',
    domains: ['steampowered.com', 'store.steampowered.com'],
    apps: ['Steam'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'gaming',
  },
  {
    id: 'epic_games',
    name: 'Epic Games',
    domains: ['epicgames.com', 'store.epicgames.com'],
    apps: ['Epic Games Launcher'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'gaming',
  },
  {
    id: 'playstation',
    name: 'PlayStation',
    domains: ['playstation.com'],
    apps: ['PlayStation'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'gaming',
  },
  {
    id: 'xbox',
    name: 'Xbox',
    domains: ['xbox.com'],
    apps: ['Xbox'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'gaming',
  },
  {
    id: 'nintendo',
    name: 'Nintendo',
    domains: ['nintendo.com'],
    apps: ['Nintendo Switch'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'gaming',
  },
  {
    id: 'gog',
    name: 'GOG',
    domains: ['gog.com'],
    apps: ['GOG Galaxy'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'gaming',
  },
  {
    id: 'battle_net',
    name: 'Battle.net',
    domains: ['battle.net'],
    apps: ['Battle.net'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'gaming',
  },
  {
    id: 'riot_games',
    name: 'Riot Games',
    domains: ['riotgames.com'],
    apps: ['Riot Client'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'gaming',
  },
  {
    id: 'ea',
    name: 'EA',
    domains: ['ea.com'],
    apps: ['EA App'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'gaming',
  },
  {
    id: 'ubisoft',
    name: 'Ubisoft',
    domains: ['ubisoft.com'],
    apps: ['Ubisoft Connect'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'gaming',
  },

  // ── Communication ─────────────────────────────────────────────────────────
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    domains: ['web.whatsapp.com'],
    apps: ['WhatsApp'],
    area: 'Personal',
    intent: 'Communicate',
    quality: 'Routine',
    confidence: 'high',
    category: 'communication',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    domains: ['web.telegram.org'],
    apps: ['Telegram'],
    area: 'Personal',
    intent: 'Communicate',
    quality: 'Routine',
    confidence: 'high',
    category: 'communication',
  },
  {
    id: 'discord',
    name: 'Discord',
    domains: ['discord.com'],
    apps: ['Discord'],
    area: 'Personal',
    intent: 'Communicate',
    quality: 'Routine',
    confidence: 'high',
    category: 'communication',
  },
  {
    id: 'slack',
    name: 'Slack',
    domains: ['slack.com', 'app.slack.com'],
    apps: ['Slack'],
    area: 'Work',
    intent: 'Communicate',
    quality: 'Routine',
    confidence: 'high',
    category: 'communication',
  },
  {
    id: 'microsoft_teams',
    name: 'Microsoft Teams',
    domains: ['teams.microsoft.com'],
    apps: ['Microsoft Teams'],
    area: 'Work',
    intent: 'Communicate',
    quality: 'Routine',
    confidence: 'high',
    category: 'communication',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    domains: ['zoom.us'],
    apps: ['Zoom'],
    area: 'Work',
    intent: 'Communicate',
    quality: 'Routine',
    confidence: 'high',
    category: 'communication',
  },
  {
    id: 'google_meet',
    name: 'Google Meet',
    domains: ['meet.google.com'],
    area: 'Work',
    intent: 'Communicate',
    quality: 'Routine',
    confidence: 'high',
    category: 'communication',
  },
  {
    id: 'skype',
    name: 'Skype',
    domains: ['skype.com'],
    apps: ['Skype'],
    area: 'Personal',
    intent: 'Communicate',
    quality: 'Routine',
    confidence: 'high',
    category: 'communication',
  },
  {
    id: 'messenger',
    name: 'Messenger',
    domains: ['messenger.com'],
    area: 'Personal',
    intent: 'Communicate',
    quality: 'Routine',
    confidence: 'high',
    category: 'communication',
  },

  // ── Social Media ──────────────────────────────────────────────────────────
  {
    id: 'instagram',
    name: 'Instagram',
    domains: ['instagram.com'],
    apps: ['Instagram'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'social',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    domains: ['facebook.com'],
    apps: ['Facebook'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'social',
  },
  {
    id: 'reddit',
    name: 'Reddit',
    domains: ['reddit.com'],
    apps: ['Reddit'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'medium',
    category: 'social',
    notes: 'Medium confidence because Reddit content varies heavily by community.',
  },
  {
    id: 'twitter',
    name: 'X / Twitter',
    domains: ['x.com', 'twitter.com'],
    apps: ['Twitter'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'medium',
    category: 'social',
    notes: 'Medium confidence because Twitter/X is often used for work communication.',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    domains: ['tiktok.com'],
    apps: ['TikTok'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'social',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    domains: ['linkedin.com'],
    apps: ['LinkedIn'],
    area: 'Work',
    intent: 'Communicate',
    quality: 'Routine',
    confidence: 'high',
    category: 'social',
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    domains: ['pinterest.com'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'social',
  },
  {
    id: 'threads',
    name: 'Threads',
    domains: ['threads.net'],
    area: 'Leisure',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'social',
  },

  // ── AI Tools ──────────────────────────────────────────────────────────────
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    domains: ['chatgpt.com'],
    apps: ['ChatGPT'],
    area: 'Work',
    intent: 'Research',
    quality: 'Focused',
    confidence: 'high',
    category: 'ai',
  },
  {
    id: 'claude',
    name: 'Claude',
    domains: ['claude.ai'],
    area: 'Work',
    intent: 'Research',
    quality: 'Focused',
    confidence: 'high',
    category: 'ai',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    domains: ['gemini.google.com'],
    area: 'Work',
    intent: 'Research',
    quality: 'Focused',
    confidence: 'high',
    category: 'ai',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    domains: ['perplexity.ai'],
    area: 'Work',
    intent: 'Research',
    quality: 'Focused',
    confidence: 'high',
    category: 'ai',
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    domains: ['copilot.microsoft.com'],
    area: 'Work',
    intent: 'Research',
    quality: 'Focused',
    confidence: 'high',
    category: 'ai',
  },
  {
    id: 'github_copilot',
    name: 'GitHub Copilot',
    apps: ['GitHub Copilot'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'ai',
    notes: 'App-only match; generic github.com is classified as GitHub.',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    apps: ['Cursor'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'ai',
  },

  // ── Shopping ──────────────────────────────────────────────────────────────
  {
    id: 'amazon',
    name: 'Amazon',
    domains: ['amazon.com', 'amazon.in', 'amazon.co.uk', 'amazon.ca', 'amazon.de'],
    apps: ['Amazon'],
    area: 'Personal',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'shopping',
  },
  {
    id: 'flipkart',
    name: 'Flipkart',
    domains: ['flipkart.com'],
    area: 'Personal',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'shopping',
  },
  {
    id: 'ebay',
    name: 'eBay',
    domains: ['ebay.com'],
    area: 'Personal',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'shopping',
  },
  {
    id: 'walmart',
    name: 'Walmart',
    domains: ['walmart.com'],
    area: 'Personal',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'shopping',
  },
  {
    id: 'etsy',
    name: 'Etsy',
    domains: ['etsy.com'],
    area: 'Personal',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'shopping',
  },
  {
    id: 'myntra',
    name: 'Myntra',
    domains: ['myntra.com'],
    area: 'Personal',
    intent: 'Consume',
    quality: 'Routine',
    confidence: 'high',
    category: 'shopping',
  },

  // ── Productivity ──────────────────────────────────────────────────────────
  {
    id: 'notion',
    name: 'Notion',
    domains: ['notion.so'],
    apps: ['Notion'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'google_docs',
    name: 'Google Docs',
    domains: ['docs.google.com'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'google_sheets',
    name: 'Google Sheets',
    domains: ['sheets.google.com'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'google_drive',
    name: 'Google Drive',
    domains: ['drive.google.com'],
    area: 'Work',
    intent: 'Organize',
    quality: 'Routine',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'microsoft_word',
    name: 'Microsoft Word',
    apps: ['Microsoft Word'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'microsoft_excel',
    name: 'Microsoft Excel',
    apps: ['Microsoft Excel'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'microsoft_powerpoint',
    name: 'Microsoft PowerPoint',
    apps: ['Microsoft PowerPoint'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'trello',
    name: 'Trello',
    domains: ['trello.com'],
    apps: ['Trello'],
    area: 'Work',
    intent: 'Organize',
    quality: 'Routine',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'asana',
    name: 'Asana',
    domains: ['asana.com'],
    apps: ['Asana'],
    area: 'Work',
    intent: 'Organize',
    quality: 'Routine',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'jira',
    name: 'Jira',
    domains: ['atlassian.net'],
    apps: ['Jira'],
    area: 'Work',
    intent: 'Organize',
    quality: 'Routine',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'linear',
    name: 'Linear',
    domains: ['linear.app'],
    apps: ['Linear'],
    area: 'Work',
    intent: 'Organize',
    quality: 'Routine',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    apps: ['Obsidian'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'evernote',
    name: 'Evernote',
    domains: ['evernote.com'],
    apps: ['Evernote'],
    area: 'Work',
    intent: 'Create',
    quality: 'Focused',
    confidence: 'high',
    category: 'productivity',
  },
  {
    id: 'todoist',
    name: 'Todoist',
    domains: ['todoist.com'],
    apps: ['Todoist'],
    area: 'Work',
    intent: 'Organize',
    quality: 'Routine',
    confidence: 'high',
    category: 'productivity',
  },
];
